<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- CDN Bootstrap 4 [CSS] -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <title>Home</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="http://localhost/examen_php/public/view/shipments/">Examen PHP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="http://localhost/examen_php/public/view/shipments/">Shipments </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost/examen_php/public/view/shipment-vehicles/">Vehicles</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row py-4">
    <div class="col">
      <div class="display-4 text-center my-3">Nuevo Envio</div>

      <form action="" method="post">
        <div class="form-group">
          <label for="inputEmail">Correo Electronico</label>
          <input type="email" class="form-control" id="inputEmail" placeholder="test@example.com" required>
        </div>
        <div class="form-group">
          <label for="inputOrder">Id de la orden</label>
          <input type="text" class="form-control" id="inputOrder" placeholder="1651513" required>
        </div>
        <div class="form-group">
          <label for="inputVehicleId">Id del vehiculo</label>
          <select class="form-control" id="inputVehicleId" required>
            <option>Seleccione un vehiculo</option>
          </select>
        </div>
        <div class="form-group">
          <label for="inputImei">Imei</label>
          <input type="text" class="form-control" id="inputImei" placeholder="asd85a32" required>
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
      </form>
    </div>
  </div>
</div>

<!-- CDN Bootstrap 4 [JS] -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<!-- CDN Font Awesome 5 [JS] -->
<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
</body>
</html>